### PR TITLE
Depending on danger-plugin-api instead of danger

### PR DESCRIPTION
**Pull request by ky1ejs**
[Danger 4.0 was recently released](https://github.com/danger/danger/releases/tag/v4.0.1), and anyone using danger-xcodebuild will not be able to use it. 

Similarly to [what danger-todoist does](https://github.com/hanneskaeufler/danger-todoist/blob/master/danger-todoist.gemspec#L21), danger-xcodebuild can depend on danger-plugin-api instead of danger, which stops the need for it having to be updated on major release of Danger if there were no significant changes to the plugin API.

### CODE REVIEW

**Comment by valeriomazzeo** [comment]
good improvement, did they introduce that recently?

**Comment by ky1ejs** [comment]
I don't think so, maybe it's not well documented. @hanneskaeufler introduced it in the [initial commit of  his project back in early September](https://github.com/hanneskaeufler/danger-todoist/tree/a8da0370b7cfa59b3855a1229a37ee306059cad1).

**Comment by valeriomazzeo** [comment]
@kylejm Thanks for your contribution 👍

**Comment by ky1ejs** [comment]
Any idea when you'll be able to make a release? :)

**Comment by hanneskaeufler** [comment]
It's mentioned [here](http://danger.systems/guides/creating_your_first_plugin.html#creating-the-plugin) there is a [template](https://github.com/danger/danger-plugin-template) you can clone, I based my plugin on this.

**Comment by valeriomazzeo** [comment]
@kylejm done 👍

**Pull request merged**
